### ISSUE TITLE
It currently doesn't work

### ISSUE THREAD

**Issue by Dutchboy** [edusperoni/ngrx-ns#1]
Hi @edusperoni  !!!

I'm very glad you've helped me out a huge way....... But I've tried to get mine and yours to compile / work - it doesn't get there.....

It's complaining of the "browser" not being defined.... I'm smiling now, because that's kinda exactly what happened with the other guy a few months ago at socketcluster-client...... 

Can you tell me which version you had when your setup worked?? Versions of nativescript-websockets and the one of socketcluster-client - both are missing in your package.json......

Hope to hear from you quickly....

Lars

**Comment by Dutchboy** [comment]
Hi @edusperoni !!!!!

I've spent my Sunday on it, time pressure - you know the works.... anyway, also your POC doesn't work without "workarounds" (the browser which doesn't exist)... and mixing removing abandoned obscure libs... 

Basically, what I've learned today (yesterday too) is that rxjs does websockets out of the box. But - these too rely on "browser". No-go.
Nativescript-websockets looks fine enough. A pitty.

But that's not what we both are looking for. We want to "connect" our state to any visualization, so that we know what we're talking about when developing (ehhh debugging) our app.

I've decided - with pain in my heart to "just develop in web". Stop, listen. I've got 13 apps here, in a monorepo, with a lot (currently 30, going strong) libs.

I saw you don't use schematics - I'm not a fan neither. So, I normally work in Webstorm, and when I have to, I switch to vcode to generate the app or lib.

I use nrwl-nx and xplat. I've deleted all the xplat code and adopted my reasoning myself. For me, the "xplat-directory" - the name of it - is confusing enough to nag me, so, "so long, fare well, auf wieder sehen goodbye" (I've never been a big fan of Nathan's coding anyway - what a mess!!!!)

But the NX - the structure is the best I've seen ever! It works finally!

So, as I mentioned, I've got 13 apps now - nativescript, web, electron (and for electron separate electronsweb's)...... These all "look" at my libs.

I've got base libs for NGRX. These NGRX files are platform agnostic.
And I've got subdirs (libs) in which the platform-specific effects and modules are residing.
The apps look at the platform-specific modules, and these modules import agnostic and specific files.

This caused me (with a lot of reluctance!) to accept - that SINCE the state-tree is the same - I could do without the visualization we both have been working on.
I DO have the visualization in "web" and look at it while programming. The only thing I don't see is when I'm working on the (nativescript) effect.......... 

There just isn't a browser!

I hope I explained my thoughts! Cheers, Lars

**Comment by edusperoni** [comment]
Hey! Those "browser" errors are because NS sets "process": undefined on webpack, and webpack needs process to use broweserified packages. the workaround is to just use "process": "global.process" and then polyfill this global.process to `require ("process/browser");`

Once I'm at the PC I can give you some better explanation, but most of the requirements are on the readme

**Comment by edusperoni** [comment]
This is the project structure:

`/` - demo app readme, license.
`/lib/` - actual library with package.json (`nativescript-websocket` deps are here)

to use it you HAVE to ensure this line is either commented or as `"process": "global.process"` https://github.com/edusperoni/ngrx-ns/blob/master/webpack.config.js#L256

You also need this: `config.plugins.push(new webpack.NormalModuleReplacementPlugin(/^ws$/, "nativescript-websockets"));` to ensure nativescript-websockets will be used instead of ws.

If process is defined as global.process, this files patches `global.process`: https://github.com/edusperoni/ngrx-ns/blob/master/lib/src/remotedev/patch.ts

You'd have to import it like this: https://github.com/edusperoni/ngrx-ns/blob/11bedd2976cdf23b667a69bb608006e08daa1435/lib/src/lib.module.ts#L1


This is all because `process` is polyfilled by webpack, but the NS team decided to remove this polyfill, which breaks some webpack libs (specifically crypto-browserify, needed by socketcluster). The logic behind this is:

1. Implement the interface between remote devtools and ngrx
2. re-add the process polyfill (allowing us to use polyfilled node modules)
3. replace `ws` with `nativescript-websockets`

When building this app, remember to run `npm install` on the `lib` directory too!

Edit: also note that you need to run `remotedev`. I added some helpers in the package.json:

https://github.com/edusperoni/ngrx-ns/blob/master/package.json#L19-L20

**Comment by edusperoni** [comment]
Just upgraded it to NS 6.0 and can confirm it's working 100%:

https://gfycat.com/ornerysociableamericanredsquirrel

**Comment by Dutchboy** [comment]
How shiny this is!!! Tomorrow I'm going to do this first thing in the morning!! Thanks a lot!!!

**Comment by Dutchboy** [comment]
Eduardo!!... You've saved my life!

Yesterday, I had everything - with just one little missing detail - I forgot to comment-out the line in webpack. Totally forgetting "these old days" - browserify...

I took the liberty to "add" you as a "FB-friend" - you never know what that brings in the future.

As for NGRX - Nativescript - Remote Redux Devtools
You are the only one - literally the ONLY one - who got this working. And there are so many (failed) attempts.... So many.....

Again, many thanks, Lars

Many thanks!
